### ISSUE TITLE
Deprecation error on jasmine 4.0

### ISSUE THREAD

**Issue by Zialus** [CodeSequence/jasmine-marbles#89]
```
ERROR: 'DEPRECATION: The matcher factory for "toBeObservable" accepts custom equality testers, but this parameter will no longer be passed in a future release. See <https://jasmine.github.io/tutorials/upgrading_to_Jasmine_4.0#matchers-cet> for details.
Error: 
    at <Jasmine>
    at addMatchers (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jasmine-marbles/es6/index.js:92:1)
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/jasmine-marbles/es6/index.js:130:1)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
```

**Comment by jrdutton** [comment]
Yep, seeing this too. Thank you for raising it.

**Comment by brandonroberts** [comment]
Would someone like to put in a PR for this?

**Comment by Zialus** [comment]
If I understand correctly, all that needs to be changed is to remove `_equalityTester` from this line
https://github.com/CodeSequence/jasmine-marbles/blob/master/index.ts#L71

**Comment by brandonroberts** [comment]
Yes, that looks correct on the change. For the release, it would be under the `0.9.x` release so you can just target the `master` branch for the PR.
